// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLuADgJD_ujKuc4onJwF3h0DAKo6mmlYM',
    appId: '1:192971924097:web:74951786537be4a1606380',
    messagingSenderId: '192971924097',
    projectId: 'flutter-base-sample-d7634',
    authDomain: 'flutter-base-sample-d7634.firebaseapp.com',
    storageBucket: 'flutter-base-sample-d7634.appspot.com',
    measurementId: 'G-CCNX4SG5KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ukFNNxXF_sfm4t341Bni4PLizpoJvfE',
    appId: '1:192971924097:android:5ebd831b0cd77359606380',
    messagingSenderId: '192971924097',
    projectId: 'flutter-base-sample-d7634',
    storageBucket: 'flutter-base-sample-d7634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUnERKHgGkbpHP9as_ZJyB1bUvpdv2Y-w',
    appId: '1:192971924097:ios:f7a685a8a5b2a026606380',
    messagingSenderId: '192971924097',
    projectId: 'flutter-base-sample-d7634',
    storageBucket: 'flutter-base-sample-d7634.appspot.com',
    iosClientId: '192971924097-ldsq7ibtaqqob20nsbknk2v5n4onmvbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUnERKHgGkbpHP9as_ZJyB1bUvpdv2Y-w',
    appId: '1:192971924097:ios:dd36221854600827606380',
    messagingSenderId: '192971924097',
    projectId: 'flutter-base-sample-d7634',
    storageBucket: 'flutter-base-sample-d7634.appspot.com',
    iosClientId: '192971924097-tmql5um30ql4nfkm3uuoi3ueit40404d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersample.RunnerTests',
  );
}
